
import java.io.File;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ธนพล
 */
public class Confirm extends javax.swing.JFrame {
    String Username = null; //ตัวแปรเก็บ Username จาก RegisterForm
    char[] password = null; //ตัวแปรเก็บ password จาก RegisterForm
    String Code = null; //ตัวแปรเก็บ ConfirmCode จาก RegisterForm
    public Confirm(String UsernameRegis,char[] passwordRegis, String CodeConfirmRegis) { //รับพารามิเตอร์3ตัวจาก RegisterForm
        initComponents();
        Username = UsernameRegis; //ให้ตัวแปร Username เก็บค่าพารามิเตอร์ตัวแรก(Username)
        password = passwordRegis; //ให้ตัวแปร password เก็บค่าพารามิเตอร์ตัวสอง(password)
        Code = CodeConfirmRegis; //ให้ตัวแปร Code เก็บค่าพารามิเตอร์ตัวสาม(confirmcode)
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfCodeConfirm = new javax.swing.JTextField();
        CodeConfirm = new javax.swing.JLabel();
        btCodeConfirm = new javax.swing.JButton();
        btCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        CodeConfirm.setText("Enter Code for Confirm:");

        btCodeConfirm.setText("Confirm");
        btCodeConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCodeConfirmActionPerformed(evt);
            }
        });

        btCancel.setText("Cancel");
        btCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btCodeConfirm)
                    .addComponent(CodeConfirm))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                        .addComponent(tfCodeConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(btCancel)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfCodeConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CodeConfirm))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCodeConfirm)
                    .addComponent(btCancel))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelActionPerformed
        dispose();     //เมื่อกดปุ่ม cancel จะปิดหน้าเดิม และเปิดหน้า login
        new LoginForm().setVisible(true);
    }//GEN-LAST:event_btCancelActionPerformed

    private void btCodeConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCodeConfirmActionPerformed
        checkConfirm();
    }//GEN-LAST:event_btCodeConfirmActionPerformed

        public void checkConfirm(){
            Connection conn = null;     
            PreparedStatement pstmt = null;
            conn = MySqlConnect.ConnectDB();   //เชื่อมต่อไปยัง Database
            if(tfCodeConfirm.getText().equals((String)Code)){  //ตรวจสอบ codeconfirm 
                try {            
                    pstmt = conn.prepareStatement("insert into member values(?,?)");  //กำหนด ข้อมูลที่จะเพิ่มใน database
                    pstmt.setString(1, Username);  
                    pstmt.setString(2,String.valueOf(password));
                    int i = pstmt.executeUpdate();  //เมื่อ database มีการ update i จะ เท่ากับ 1
                    File newFile = new File("C:\\Users\\ธนพล\\Desktop\\SakNoi\\building II\\LoginField\\StorefolderUser\\"+Username);
                    newFile.mkdir();  //สร้าง folder ตามชื่อ Username เพื่อเก็บไฟล์ pdf ของแต่ละ user
                    System.out.println("Create Folder for User "+Username+" Successful!!");
                    if(i>0){  // เมื่อมีการ update แจ้งเตือน
                        JOptionPane.showMessageDialog(null, "Regis successful");  
                        System.out.println("Register Successful!");
                        dispose(); //ปิดหน้าต่าง confirm 
                        LoginForm login = new LoginForm(); 
                        login.setVisible(true); //เปิดหน้า login
                    }else{
                        JOptionPane.showMessageDialog(null, "Regis fail"); //เมื่อไม่มีการ update ข้อมูลจาก database(สมัครไม่สำเร็จ) จะทำการแจ้งเตือนว่าสมัครไม่สำเร็จ
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(Confirm.class.getName()).log(Level.SEVERE, null, ex);
                }
            }else{ //เมื่อส่ง CodeConfirm ไม่สำเร็จจะแจ้งเตือน
                System.out.println("Send ConfirmCode Fail");
            }
        }
    /**
     * @param args the command line arguments
     */

    void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Confirm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Confirm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Confirm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Confirm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Confirm(Username,password,Code).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CodeConfirm;
    private javax.swing.JButton btCancel;
    private javax.swing.JButton btCodeConfirm;
    private javax.swing.JTextField tfCodeConfirm;
    // End of variables declaration//GEN-END:variables
}
