
import java.awt.HeadlessException;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ธนพล
 */
public class LoginForm extends javax.swing.JFrame {
        Connection conn = null;
        PreparedStatement ps = null;
        ResultSet rs = null;
    /**
     * Creates new form LoginForm
     */
    public LoginForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbUsername = new javax.swing.JLabel();
        tfUsername = new javax.swing.JTextField();
        pfPassword = new javax.swing.JPasswordField();
        lbPassword = new javax.swing.JLabel();
        bLogin = new javax.swing.JButton();
        bClear = new javax.swing.JButton();
        lbTextRegister = new javax.swing.JLabel();
        bRegister = new javax.swing.JButton();
        lbTitle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        lbUsername.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        lbUsername.setForeground(new java.awt.Color(0, 0, 255));
        lbUsername.setText("Username:");

        lbPassword.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        lbPassword.setForeground(new java.awt.Color(0, 0, 255));
        lbPassword.setText("Password:");

        bLogin.setText("Login");
        bLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLoginActionPerformed(evt);
            }
        });

        bClear.setText("Clear");
        bClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bClearActionPerformed(evt);
            }
        });

        lbTextRegister.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        lbTextRegister.setForeground(new java.awt.Color(255, 0, 0));
        lbTextRegister.setText("If your don't member:");

        bRegister.setText("Register");
        bRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRegisterActionPerformed(evt);
            }
        });

        lbTitle.setFont(new java.awt.Font("Tempus Sans ITC", 1, 36)); // NOI18N
        lbTitle.setForeground(new java.awt.Color(0, 204, 0));
        lbTitle.setText("Personal Library Login");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbPassword)
                            .addComponent(lbUsername))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pfPassword)
                            .addComponent(tfUsername)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbTextRegister)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bRegister, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(bLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bClear, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)))
                .addGap(100, 100, 100))
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(lbTitle)
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(lbTitle)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbUsername)
                    .addComponent(tfUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbPassword))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bLogin)
                    .addComponent(bClear))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTextRegister)
                    .addComponent(bRegister))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bClearActionPerformed
        tfUsername.setText(""); //เมื่อกดปุ่ม clear จะทำการset Username ให้ว่าง
        pfPassword.setText("");//เมื่อกดปุ่ม clear จะทำการset password ให้ว่าง
    }//GEN-LAST:event_bClearActionPerformed

    private void bLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLoginActionPerformed
       conn  = MySqlConnect.ConnectDB();  //เชื่อต่อกับ database
       String Sql = "SELECT `Username`, `Password` FROM `member` WHERE `Username` = ? AND `Password` = ?"; // ข้อความส่งไป database
       try{
           ps = conn.prepareStatement(Sql);
           ps.setString(1,tfUsername.getText()); // Username ที่ส่ง
           ps.setString(2,pfPassword.getText()); // password ที่สง
           rs=ps.executeQuery();
           
           if(rs.next()){ 
               JOptionPane.showMessageDialog(null, "welcome "+tfUsername.getText());
               String folderUser = "C:\\Users\\ธนพล\\Desktop\\SakNoi\\building II\\LoginField\\StorefolderUser\\"+tfUsername.getText();//ชื่อ path ของfolder ที่จะสร้างของแต่ละ User
               MyFormApp app = new MyFormApp(folderUser); //สร้าง หน้าต่างแสดงรายชื่อหนังสือและส่ง path ไปให้ 
               app.setVisible(true); //เปิดหน้าต่างแสดงายชื่อหนังสือ
               dispose(); //ปิดหน้าต่างเดิม(login)
           }else{
               JOptionPane.showMessageDialog(null, "Username or Password is wrong");
           }
       }catch(SQLException | HeadlessException e){
           JOptionPane.showMessageDialog(null,e);
       }           
    }//GEN-LAST:event_bLoginActionPerformed

    private void bRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRegisterActionPerformed
        dispose();  //เมื่อกดปุ่ม สมัคร(Register) จะปิดหน้าต่างเดิม และสร้างหน้าต่าง Register ขึ้นมา
        RegisterForm register = new RegisterForm();
        register.setVisible(true);
    }//GEN-LAST:event_bRegisterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
            //</editor-fold>
            
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new LoginForm().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bClear;
    private javax.swing.JButton bLogin;
    private javax.swing.JButton bRegister;
    private javax.swing.JLabel lbPassword;
    private javax.swing.JLabel lbTextRegister;
    private javax.swing.JLabel lbTitle;
    private javax.swing.JLabel lbUsername;
    private javax.swing.JPasswordField pfPassword;
    private javax.swing.JTextField tfUsername;
    // End of variables declaration//GEN-END:variables
}
